# Generated by Django 4.2.2 on 2023-08-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="pid",
            field=models.IntegerField(default=-1),
        ),
    ]
