# Generated by Django 4.2.2 on 2023-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_info", "0002_node_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="status",
            field=models.IntegerField(choices=[(0, "free"), (1, "working")], default=0),
        ),
    ]
