# Generated by Django 4.2.2 on 2025-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_info', '0003_node_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='keepalive',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
